version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: companyManagerDb
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Pass1234$
    ports:
      - 1433:1433
        
  rabbitmq:
    image: rabbitmq:3-management
    container_name: companyManagerRabbitMq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest