version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: companyManagerDb
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Pass1234$
    ports:
      - 1433:1433
        
  rabbitmq:
    image: rabbitmq:3-management
    container_name: companyManagerRabbitMq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
        
  companymanager-ids:
    image: vazaras/companymanager-ids:latest
    container_name: companyManagerIds
    ports:
      - 16000:80
      - 16001:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=16001
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=host.docker.internal,1433;Initial Catalog=CompanyManagerIdentityServerDatabase;Persist Security Info=False;User ID=sa;Password=Pass1234$;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
      - SWAGGER_REDIRECT_URI=https://localhost:15001/swagger/oauth2-redirect.html
      - SWAGGER_ALLOWED_CORS_ORIGINS=https://localhost:15001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass123$
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/companymanager-ids.pfx
    depends_on:
      - sqlserver
      - rabbitmq
    volumes:
      - ${HOME}/.aspnet/https:/https/
      - ${HOME}/.keys:/app/keys
      
  companymanager-api:
    image: vazaras/companymanager-api:latest
    container_name: companyManagerApi
    ports:
      - 15000:80
      - 15001:443
    depends_on:
      - sqlserver
      - rabbitmq
      - companymanager-ids
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=15001
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=host.docker.internal,1433;Initial Catalog=CompanyManagerDatabase;Persist Security Info=False;User ID=sa;Password=Pass1234$;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - IDS_AUTHORITY=https://localhost:16001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass123$
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/companymanager-api.pfx
    volumes:
      - ${HOME}/.aspnet/https:/https/